import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useToasts } from "react-toast-notifications";
import styles from "styles/containers/cms/Login.module.scss";

const Home: NextPage = () => {
  const router = useRouter();
  const { addToast } = useToasts();
  useEffect(() => {
    if (router.query.error) {
      addToast(`Unauthorized`, {
        appearance: "info",
        autoDismiss: true,
      });
    }
  }, [router.query]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Login to CMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/api/auth/signin/saml">Login</Link>
    </div>
  );
};

export default Home;
